var introStructure = new TimelineLite()
	introStructure
	.staggerTo('.topline', 0.2, {width: "100%"}, .15, "stagger")
	.to('.right-upper', .1, {height: "100%"})
	.to('.right-lower', .1, {height: "100%"})
	.to('.bottomline-2', .2, {width: "100%"})
	.to('.bottomline-1', .2, {width: "100%"})
	.to('.left', .2, {height: "100%"})
	introStructure.delay(0.3)
var introStructureText = new TimelineLite()
	introStructureText
	.to('.link-1', 0.5, {opacity: 1}, 0.5)
	.to('.link-2', 0.5, {opacity: 1}, 0.6)
	.to('.link-wrap', 0.5, {opacity: 1}, 0.9)
	.to('#title', 0.3, {top: 0}, 1.1)
var introStructureButtont = new TimelineLite()
	introStructureButtont
	.staggerTo('.menu span', 0.3, {width: "100%"}, 0.1, "stagger")
	introStructureButtont.delay(0.5)
var introStructureLinks = new TimelineLite()
	introStructureLinks
	.to('.nav-3', 0.2, {opacity: 1})
	.to('.nav-2', 0.2, {opacity: 1})
	.to('.nav-1', 0.2, {opacity: 1})
	introStructureLinks.delay(1.6)